name: Build in docker

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  REPO_GIT_HASH: ${{ github.sha }}

jobs:
  example-job:
    runs-on: ubuntu-latest
    container: centos:centos7.9.2009

    steps:

    - name: display env var
      run: echo REPO_GIT_HASH=$REPO_GIT_HASH

    - name: Check for dockerenv file
      run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

    - name: uname 
      run: uname -a

    - name: /proc/version
      run: cat /proc/version

    - name: /etc/redhat-release
      run: cat /etc/redhat-release

    - name: /etc/issue
      run: cat /etc/issue


# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:

#     - uses: actions/checkout@v3

#     - name: display rust version
#       run: rustup --version

#     - name: display repo git hash
#       run: echo REPO_GIT_HASH=$REPO_GIT_HASH

#     - name: build project
#       run: cd nrelay && cargo build
      
#     - name: display out_version
#       run: pwd && realpath out_version.txt && cat out_version.txt

